### ISSUE TITLE
Dependencies vs dev dependencies

### ISSUE THREAD

**Issue by LOBsTerr** [openeuropa/oe_content#332]
### Problem

Open content module provides quite a lot of module as dev dependencies, but at the same time sub modules have dependencies in the config. One small example. **oe_content_event** has config 

https://github.com/openeuropa/oe_content/blob/master/modules/oe_content_event/config/install/core.entity_form_display.node.oe_event.default.yml

This config has dependency on **inline_entity_form**, but for **oe_content** **inline_entity_form** is dev dependency.

As result when I run composer require openeuropa/oe_content. I never will have **inline_entity_form** installed, because composer doesn't install dev dependencies of sub packages. Only the dev dependencies of the current package.

###  Solution 
Move all direct dependencies from **require-dev** section to require-dev

**Comment by brummbar** [comment]
This cannot be done, as you would be forcing the dependencies of ALL the submodules, even those that are not enabled, to be required and installed.
For example, if I just install the module oe_content_page, I don't need inline_entity_form, and I shouldn't be forced to have it downloaded, nor to inherit the constraints that would be forced by oe_content in that case.
That's why we have a README in each sub module, where we explain which dependencies are required to be added in the user's composer.json in order to use the submodule: https://github.com/openeuropa/oe_content/tree/master/modules/oe_content_event#installation
The dependency is then forced in the info.yml of the submodule itself.
